# GPU SGLang runtime image used by verl release/v0.9.0 CI.
FROM verlai/verl:sgl0512.dev4

ARG VERL_REF=release/v0.9.0
ARG VERL_REPO=https://github.com/verl-project/verl.git

WORKDIR /workspace

RUN git clone ${VERL_REPO} /workspace/verl \
    && cd /workspace/verl \
    && git checkout ${VERL_REF} \
    && pip install -e .

COPY . /workspace/verl-SpeCo

WORKDIR /workspace/verl-SpeCo
RUN pip install -e .
